### ISSUE TITLE
Unable to add item -> entity mappings through datapack

### ISSUE THREAD

**Issue by NillerMedDild** [ExpensiveKoala/Fishing-Real#1]
Hello o/

I could use some help with getting the datapack made correctly, as I can't seem to get it right. Would you mind having a look at what I have currently?

[enigmatica.zip](https://github.com/ExpensiveKoala/Fishing-Real/files/3801699/enigmatica.zip)

Bonus info: The datapack works, as the other namespace in there is working without issues.

**Comment by NillerMedDild** [comment]
Bonus info: The log is throwing malformed json errors, one for each fish file I've added, but the jsons are valid. Example
```
16:45:43] [Server-Worker-160/ERROR]: Couldn't parse data file enigmatica:arapaima from enigmatica:fishing/arapaima.json
com.google.gson.JsonParseException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1 path $
	at net.minecraft.util.JSONUtils.func_188173_a(SourceFile:495) ~[?:?]
	at net.minecraft.util.JSONUtils.func_193839_a(SourceFile:533) ~[?:?]
	at net.minecraft.client.resources.JsonReloadListener.func_212854_a_(JsonReloadListener.java:48) ~[?:?]
	at net.minecraft.client.resources.JsonReloadListener.func_212854_a_(JsonReloadListener.java:22) ~[?:?]
	at net.minecraft.client.resources.ReloadListener.func_215270_b(SourceFile:11) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) [?:1.8.0_191]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) [?:1.8.0_191]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_191]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_191]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_191]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_191]
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559) ~[gson-2.8.0.jar:?]
	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1401) ~[gson-2.8.0.jar:?]
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:593) ~[gson-2.8.0.jar:?]
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:425) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:716) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:714) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$35$1.read(TypeAdapters.java:910) ~[gson-2.8.0.jar:?]
	at net.minecraft.util.JSONUtils.func_188173_a(SourceFile:493) ~[?:?]
	... 10 more
```

**Comment by ExpensiveKoala** [comment]
It seems the files are unicode encoded. Change it to ANSI or another one.

**Comment by NillerMedDild** [comment]
That was it, changed to UTF-8 and all as well now, thank you very much! I was starting to think I was insane :P
